version: '3.8'

services:

  # Gateway
  dude_gateway:
    build: ./gateway-service # Directory to build the service from
    ports:
      - '3000:3000' # Map the container port to the host port
    depends_on:
      - dude_data_service # Depend on the dude_data_service service
      - dude_user_service # Depend on the dude_user_service service

  # data-service
  dude_data_service:
    build: ./data-service # Directory to build the service from
    depends_on:
      - dude_mongo_data # Depend on the dude_mongo_data service

  # user-service
  dude_user_service:
    build: ./user-service # Directory to build the service from
    depends_on:
      - dude_mongo_user # Depend on the dude_mongo_user service

  # data-service DB
  dude_mongo_data:
    image: mongo # Use the mongo image
    container_name: dude_mongo_data # Set the container name
    volumes:
      - dude_data_db:/data/db # Define a volume and map it to the container
    ports:
      - '27018:27017' # Map the container port to the host port

  # user-service DB
  dude_mongo_user:
    image: mongo # Use the mongo image
    container_name: dude_mongo_user # Set the container name
    volumes:
      - dude_user_db:/data/db # Define a volume and map it to the container
    ports:
      - '27019:27017' # Map the container port to the host port

# Define named volumes for persistent data storage, so that the data is not lost when the container is destroyed
volumes:
  dude_data_db:
  dude_user_db:
